Repository overtools/OWLib, pull requests merged in 2020-04, with the labels that each got.

#79 smol tweaks
  DataTool/ToolLogic/Extract/ExtractHeroUnlocks.cs
  DataTool/ToolLogic/List/Misc/ListBrawls.cs
  DataTool/ToolLogic/List/Misc/ListChatReplacements.cs
  DataTool/ToolLogic/List/Misc/ListConversations.cs
  DataTool/ToolLogic/List/Misc/ListProfanityFilter.cs
  DataTool/ToolLogic/List/Misc/ListWorkshop.cs
  TankLib/STU/Types/Enums/Enum_43D38C2E.cs
  TankLib/STU/Types/Enums/Enum_542A081B.cs
  TankLibHelper/Data/KnownEnumNames.csv
Labels: datatool, enhancement

#80 ReplayMp4Tool now with less crashes
  ReplayMp4Tool/MP4Atom.cs
  ReplayMp4Tool/Program.cs
  ReplayMp4Tool/ReplayMp4Tool.csproj
  ReplayMp4Tool/ReplayThing.cs
  ReplayMp4Tool/packages.config
Labels: enhancement, old-dev

#83 [ReplayMp4Tool] added FilePath output to json
  ReplayMp4Tool/ReplayThing.cs
Labels: enhancement
